In [3]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

In [4]:
cancer = load_breast_cancer()

In [10]:
x = cancer.data
y = cancer.target
x.shape, y.shape

((569, 30), (569,))

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state = 2022,shuffle = True)

In [16]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape =(30,)))
model.add(keras.layers.Dense(60, activation = 'relu'))
model.add(keras.layers.Dense(60, activation = 'relu'))
model.add(keras.layers.Dense(1, activation = 'sigmoid'))

model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 60)                1860      
                                                                 
 dense_1 (Dense)             (None, 60)                3660      
                                                                 
 dense_2 (Dense)             (None, 1)                 61        
                                                                 
Total params: 5,581
Trainable params: 5,581
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.fit(x_train, y_train, verbose = 1, epochs = 10)

Epoch 1/10
13/13 [==============================] - 0s 3ms/step - loss: 0.2950 - accuracy: 0.9070
Epoch 2/10
13/13 [==============================] - 0s 3ms/step - loss: 0.2732 - accuracy: 0.9045
Epoch 3/10
13/13 [==============================] - 0s 2ms/step - loss: 0.2418 - accuracy: 0.9045
Epoch 4/10
13/13 [==============================] - 0s 2ms/step - loss: 0.1896 - accuracy: 0.9271
Epoch 5/10
13/13 [==============================] - 0s 3ms/step - loss: 0.1979 - accuracy: 0.9271
Epoch 6/10
13/13 [==============================] - 0s 3ms/step - loss: 0.2107 - accuracy: 0.9196
Epoch 7/10
13/13 [==============================] - 0s 2ms/step - loss: 0.1920 - accuracy: 0.9296
Epoch 8/10
13/13 [==============================] - 0s 2ms/step - loss: 0.1900 - accuracy: 0.9246
Epoch 9/10
13/13 [==============================] - 0s 3ms/step - loss: 0.1853 - accuracy: 0.9271
Epoch 10/10
13/13 [==============================] - 0s 2ms/step - loss: 0.2145 - accuracy: 0.9246


In [23]:
y_pred = model.predict(x_test)
print(y_pred.reshape(-1).round(0)[:10])
print(y_test[:10])

[1. 1. 1. 1. 1. 1. 1. 0. 1. 0.]
[1 1 0 1 1 1 1 0 0 0]


In [32]:
keras.backend.clear_session()

il = keras.layers.Input(shape = (30,))
hl = keras.layers.Dense(60, activation = 'relu')(il)
hl = keras.layers.Dense(70, activation = 'relu')(hl)
ol = keras.layers.Dense(1, activation = 'sigmoid')(hl)

model = keras.models.Model(il,ol)

model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 30)]              0         
                                                                 
 dense (Dense)               (None, 60)                1860      
                                                                 
 dense_1 (Dense)             (None, 70)                4270      
                                                                 
 dense_2 (Dense)             (None, 1)                 71        
                                                                 
Total params: 6,201
Trainable params: 6,201
Non-trainable params: 0
_________________________________________________________________


In [33]:
model.fit(x_train, y_train, verbose = 1, epochs = 10, validation_split=0.2)

Epoch 1/10
10/10 [==============================] - 1s 35ms/step - loss: 5.3446 - accuracy: 0.5786 - val_loss: 1.6171 - val_accuracy: 0.8000
Epoch 2/10
10/10 [==============================] - 0s 7ms/step - loss: 1.2939 - accuracy: 0.7673 - val_loss: 0.1777 - val_accuracy: 0.9375
Epoch 3/10
10/10 [==============================] - 0s 8ms/step - loss: 0.7767 - accuracy: 0.8239 - val_loss: 0.9369 - val_accuracy: 0.6875
Epoch 4/10
10/10 [==============================] - 0s 8ms/step - loss: 0.7781 - accuracy: 0.8270 - val_loss: 0.2902 - val_accuracy: 0.9000
Epoch 5/10
10/10 [==============================] - 0s 7ms/step - loss: 0.3297 - accuracy: 0.8836 - val_loss: 0.1824 - val_accuracy: 0.9625
Epoch 6/10
10/10 [==============================] - 0s 7ms/step - loss: 0.2565 - accuracy: 0.9057 - val_loss: 0.0984 - val_accuracy: 0.9625
Epoch 7/10
10/10 [==============================] - 0s 7ms/step - loss: 0.2064 - accuracy: 0.9151 - val_loss: 0.0952 - val_accuracy: 0.9625
Epoch 8/10
10/10 [=

In [35]:
y_pred = model.predict(x_test)
print(y_pred.reshape(-1).round(0)[:10])

[1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
