In [3]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

In [4]:
boston = load_boston()

C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i

In [5]:
x = boston.data
y = boston.target

In [8]:
x.shape, y.shape

((506, 13), (506,))

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state=2022)

In [10]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape = (13,)))
model.add(keras.layers.Dense(36, activation = 'relu'))
model.add(keras.layers.Dense(36, activation = 'relu'))
model.add(keras.layers.Dense(1))

model.compile(loss = 'mse', optimizer = 'adam')

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 36)                504       
                                                                 
 dense_1 (Dense)             (None, 36)                1332      
                                                                 
 dense_2 (Dense)             (None, 1)                 37        
                                                                 
Total params: 1,873
Trainable params: 1,873
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.fit(x_train, y_train, verbose = 1, epochs = 10, validation_split = 0.2)

Epoch 1/10
9/9 [==============================] - 0s 14ms/step - loss: 44.1094 - val_loss: 48.1310
Epoch 2/10
9/9 [==============================] - 0s 8ms/step - loss: 47.6955 - val_loss: 53.8158
Epoch 3/10
9/9 [==============================] - 0s 8ms/step - loss: 43.4273 - val_loss: 28.1666
Epoch 4/10
9/9 [==============================] - 0s 8ms/step - loss: 41.5003 - val_loss: 25.5416
Epoch 5/10
9/9 [==============================] - 0s 8ms/step - loss: 40.6161 - val_loss: 26.7986
Epoch 6/10
9/9 [==============================] - 0s 8ms/step - loss: 43.2656 - val_loss: 35.3215
Epoch 7/10
9/9 [==============================] - 0s 8ms/step - loss: 39.9373 - val_loss: 24.9395
Epoch 8/10
9/9 [==============================] - 0s 7ms/step - loss: 38.3443 - val_loss: 23.6527
Epoch 9/10
9/9 [==============================] - 0s 7ms/step - loss: 42.3762 - val_loss: 22.9322
Epoch 10/10
9/9 [==============================] - 0s 8ms/step - loss: 39.4621 - val_loss: 23.3160


In [17]:
y_pred = model.predict(x_test)
print(y_pred.reshape(-1)[:5])
print(y_test[:5])

[22.941036 13.77476  21.265392 30.059948 20.101116]
[20.1 11.9 20.6 33.2 20.8]


In [18]:
keras.backend.clear_session()

il = keras.layers.Input(shape = (13,))
hl = keras.layers.Dense(36, activation = 'relu')(il)
hl = keras.layers.Dense(36, activation = 'relu')(hl)
ol = keras.layers.Dense(1)(hl)

model = keras.models.Model(il,ol)

model.compile(loss = 'mse', optimizer = 'adam')

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 13)]              0         
                                                                 
 dense (Dense)               (None, 36)                504       
                                                                 
 dense_1 (Dense)             (None, 36)                1332      
                                                                 
 dense_2 (Dense)             (None, 1)                 37        
                                                                 
Total params: 1,873
Trainable params: 1,873
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.fit(x_train, y_train, verbose = 1, epochs = 10, validation_split=0.2)

Epoch 1/10
9/9 [==============================] - 0s 14ms/step - loss: 69.0624 - val_loss: 53.7299
Epoch 2/10
9/9 [==============================] - 0s 8ms/step - loss: 67.7076 - val_loss: 49.6142
Epoch 3/10
9/9 [==============================] - 0s 8ms/step - loss: 66.6069 - val_loss: 46.9672
Epoch 4/10
9/9 [==============================] - 0s 8ms/step - loss: 62.8431 - val_loss: 53.5361
Epoch 5/10
9/9 [==============================] - 0s 9ms/step - loss: 64.3259 - val_loss: 53.8244
Epoch 6/10
9/9 [==============================] - 0s 8ms/step - loss: 65.8867 - val_loss: 42.3584
Epoch 7/10
9/9 [==============================] - 0s 7ms/step - loss: 63.6870 - val_loss: 41.0185
Epoch 8/10
9/9 [==============================] - 0s 8ms/step - loss: 62.2803 - val_loss: 48.2270
Epoch 9/10
9/9 [==============================] - 0s 8ms/step - loss: 66.1382 - val_loss: 39.5679
Epoch 10/10
9/9 [==============================] - 0s 8ms/step - loss: 70.6351 - val_loss: 44.3370


In [21]:
y_pred = model.predict(x_test)
print(y_pred.reshape(-1)[:5])

[21.564287 15.628753 22.911963 26.03309  18.299112]
